
image:
  name: traefik
  # v3.0 ainda em beta
  tag: "v3.0"

persistence:
  enabled: true

logs:
  general:
    level: DEBUG

ingressRoute:
  dashboard:
    enabled: false
    # # Additional ingressRoute annotations (e.g. for kubernetes.io/ingress.class)
    # annotations: {}
    # # Additional ingressRoute labels (e.g. for filtering IngressRoute by custom labels)
    # labels: {}
    # # The router match rule used for the dashboard ingressRoute
    # matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    # # Specify the allowed entrypoints to use for the dashboard ingress route, (e.g. traefik, web, websecure).
    # # By default, it's using traefik entrypoint, which is not exposed.
    # # /!\ Do not expose your dashboard without any protection over the internet /!\
    # entryPoints: ["websecure"]

additionalArguments:
  # - "--certificatesresolvers.lestaging.acme.tlschallenge=true"
  # - "--certificatesresolvers.lestaging.acme.email=exemplo@vee.codes"
  # - "--certificatesresolvers.lestaging.acme.storage=/data/acme-staging.json"
  # - "--certificatesresolvers.lestaging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  - "--certificatesresolvers.leproduction.acme.tlschallenge=true"
  - "--certificatesresolvers.leproduction.acme.email=exemplo@vee.codes"
  - "--certificatesresolvers.leproduction.acme.storage=/data/acme.json"

# not working
# certResolver:
#   lestaging:
#     email: exemplo@vee.codes
#     tlsChallenge: true
#     storage: /data/acme-staging.json
#     caserver: "https://acme-staging-v02.api.letsencrypt.org/directory"
#   leproduction:
#     email: exemplo@vee.codes
#     tlsChallenge: true
#     storage: /data/acme.json

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:1.35
      command: ["sh", "-c", "touch /data/acme.json && touch /data/acme-staging.json && chmod -Rv 600 /data/* && chown 65532:65532 /data/acme*.json"]
      volumeMounts:
        - name: data
          mountPath: /data
