#
# Configuração simples para Docker Engine local
#
version: '3'

services:
  traefik:
    image: traefik:v3.0 # ainda beta
    command: 
      - "--providers.docker"
      #- "--log.level=DEBUG"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=exemplo@vee.codes"
      - "--certificatesresolvers.myresolver.acme.storage=/opt/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    volumes:
      # Bind do socket do Docker
      - /var/run/docker.sock:/var/run/docker.sock
      - "/opt/letsencrypt:/opt/letsencrypt"
    ports:
      # Portas HTTP e HTTPS
      - "80:80"
      - "443:443"

  webapp1:
    image: containous/whoami
    labels:
      - "traefik.http.routers.webapp1.rule=Host(`app1.labs.vee.codes`)"
      #- "traefik.http.routers.webapp1.entrypoints=websecure"
      #- "traefik.http.routers.webapp1.tls.certresolver=myresolver"
    command:
      - "--name=app1"

  webapp2:
    image: containous/whoami
    labels:
      - "traefik.http.routers.webapp2.rule=Host(`app2.labs.vee.codes`)"
      #- "traefik.http.routers.webapp2.entrypoints=websecure"
      #- "traefik.http.routers.webapp2.tls.certresolver=myresolver"
    command:
      - "--name=app2"

